#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Requirements:
#
#    Configure HAproxy with version equal or greater than 1.5 so that it send traffic to web-01 and web-02
#    Distribute requests using a roundrobin algorithm
#    Make sure that HAproxy can be managed via an init script
#    Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02. If not, follow this tutorial.
#    For your answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements


sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 1091-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 1091-web-01 35.237.235.204:80 check\n\tserver 1091-web-02 34.73.24.78:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
