#!/usr/bin/env bash
# ink sites-enabled to sites-available
# start nginx without running status
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
rm /run/nginx.pid
