#!/usr/bin/env bash
#  displays the content of the file /etc/passwd as a story

while _=":" read USERNAME PASS USR_ID GRP_ID USR_INFO HOME_DIR CMD_SHELL; do
    echo "The user $USERNAME is part of the $GRP_ID gang, lives in $HOME_DIR and rides $CMD_SHELL. $USR_ID's place is protected by the passcode $PASS, more info about the user here: $USR_INFO"
done < /etc/passwd
