#!/usr/bin/env bash
#  4 "bad luck" for the 4th loop iteration
#  8 "good luck" for the 8th loop iteration
#  other "Holberton School"
COUNTER=1
while [ "$COUNTER" -le 10 ]; do
    if [ $COUNTER -eq 4 ]; then
	echo "bad luck"
    elif [ $COUNTER -eq 8 ]; then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let COUNTER=COUNTER+1
done