#!/usr/bin/env bash
# "bad luck from China" 4th iteration
# "bad luck from Japan" 9th iteration
# "bad luck from Italy" 17th iteration

COUNT=1
while [ "$COUNT" -le 20 ]; do
    echo "$COUNT"
    case "$COUNT" in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    let COUNT=COUNT+1
done
